import Head from "next/head";
import { MainProps } from "../../model";
import { withMainLayout } from "@/src/widget/layouts/ui";
import { FirstLevelNavigation } from "@/src/entity/topPage/ui";

const MainPage: React.FC<MainProps> = ({ menu, category }) => {
  return (
    <>
      <Head>
        <title>Owl top</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FirstLevelNavigation />
    </>
  );
};

const MainPageWithLayout = withMainLayout(MainPage);

export { MainPageWithLayout };
