import { CustomButton, Title } from "@/src/shared/ui";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title as="h1">Заголовок 2</Title>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis, debitis. Quisquam
        distinctio iste fugiat, ea magni recusandae repellat ullam odio omnis vel asperiores porro
        impedit beatae exercitationem. Culpa, ut quis!
      </p>
      <CustomButton appearance="primary" arrow="down">
        Test
      </CustomButton>
    </>
  );
}

